const nspell = require("nspell");

const dic = [
  "100",
  "Cassowary",
  "CHR.js",
  "Google Polymer",
  "Dojo Toolkit",
  "jQuery",
  "midori",
  "MooTools",
  "Prototype JavaScript Framework",
  "AnyChart",
  "Babylon.js",
  "Chart.js",
  "Cytoscape",
  "D3.js",
  "Dojo Toolkit",
  "FusionCharts",
  "Google Charts",
  "Highcharts",
  "JavaScript InfoVis Toolkit",
  "p5.js",
  "Plotly",
  "Processing.js",
  "Raphaël",
  "RGraph",
  "SWFObject",
  "Teechart",
  "Three.js",
  "Velocity.js",
  "Verge3D",
  "Webix",
  "Angular",
  "AngularJS",
  "Bootstrap",
  "Dojo Widgets",
  "Ext JS by Sencha",
  "Foundation by ZURB",
  "jQuery UI",
  "jQWidgets",
  "OpenUI5 by SAP",
  "Polymer",
  "qooxdoo",
  //   "React.js",
  "Vue.js",
  "Webix",
  "WinJS",
  "Svelte",
  "Glow",
  "Lively Kernel",
  "Script.aculo.us",
  "YUI Library",
  "Google Closure Library",
  "Joose",
  "JsPHP",
  "Microsoft's Ajax library",
  "MochiKit",
  "PDF.js",
  "Socket.IO",
  "Spry framework",
  "Underscore.js",
  "jQuery Mobile",
  "Mustache",
  "Jinja-JS",
  "Twig.js",
  "Jasmine",
  "Mocha",
  "QUnit",
  "Unit.js",
  "Angular",
  "AngularJS",
  "Backbone.js",
  "Cappuccino",
  "Chaplin.js",
  "Echo",
  "Ember.js",
  "Enyo",
  "Express.js",
  "Ext JS",
  "Google Web Toolkit",
  "JavaScriptMVC",
  "JsRender/JsViews",
  "Knockout",
  "Meteor",
  "Mojito",
  "MooTools",
  "OpenUI5",
  "Polymer",
  "Prototype JavaScript Framework",
  "PureMVC",
  "qooxdoo",
  "*React.js",
  "SproutCore",
  "Vue.js",
  "Wakanda Framework",
  "Blockly",
  "Cannon.js",
  "MathJax",
  "Modernizr",
  "TensorFlow",
];

const aff = `SET UTF-8`;

const spell = nspell(aff, dic.join("\n"));

console.log(spell.suggest("ext"));
console.log(spell.suggest("vue.js"));
console.log(spell.suggest("Mocha.js"));
console.log(spell.suggest("react"));
console.log(spell.suggest("reactjs"));
console.log(spell.suggest("Google Charts1"));
console.log(spell.suggest("Google   Charts1"));
console.log(spell.suggest("Vue.js React.js Angulara"));
console.log(spell.suggest("Angulara"));
console.log(spell.suggest("Vue. js"));

console.log(0);
