on:
  push:
    branches:
      - test/actions/condition

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: echo Start
      - if: success()
        run: echo c1
      - if: matrix.os == 'ubuntu-latest'
        run: echo c2
      - if: startsWith( github.ref, 'refs/tags/releases/')
        run: echo c3
      - name: Publish
        if: success() && startsWith( github.ref, 'refs/tags/releases/') && matrix.os == 'ubuntu-latest'
        run: echo Publish
